<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>KEYCLOAK</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>3244898a-38a9-4080-b3c2-fe3fae9065e4</testSuiteGuid>
   <testCaseLink>
      <guid>702c4f8b-d8ad-456b-9720-70c9fb88323d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Yoda_Station/Keyclock/002 - Yoda Portal Access - First Login to Yoda with country choice</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>19dc523d-7ba4-4987-8a75-a16c2f7fccd4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>89ad666a-d16e-4bc5-917e-fa338dd6e627</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c88d8e80-6354-444a-ac5c-343a273b3c34</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4acdb63f-bbd8-4192-8cce-1baf67e67c22</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Yoda_Station/Keyclock/003 - Yoda Portal Access - First Login with chosen project</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>457b4a40-df75-4675-b34f-544bd1101fed</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>37fa80ba-cc3d-4e7c-a8c2-8e9f7bb108ee</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>741f3f8c-6bab-4c35-bedb-1c8963919fd0</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>12666244-86ca-4d13-b724-da4e6f100ae1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Yoda_Station/Keyclock/004 - Yoda Portal Access - Delete User</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>97d5fcbb-a6b7-4de5-ba63-f2a890c76965</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4337e9f6-e93f-4b5e-89af-6d361b5cb291</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6c89305b-99bc-4c9d-ab56-013af9e389d7</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6b3d941d-c8f0-4812-ac7c-807a1d3db38c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Yoda_Station/Keyclock/005 - Yoda Portal Access - First Login to Yoda</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c34d420e-ad49-45ea-af2e-cf289d2466a5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f5e40762-834b-46ae-a739-d199a2b264ae</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7a064bfc-9f0e-4ebc-a037-994711e74707</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>65403967-fe4a-4a99-8775-74a3b6bd7d0a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Yoda_Station/Keyclock/006 - Yoda Portal Access - User already logged to Yoda</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>13495380-7052-44e0-860d-c91553b3355c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>83d69437-0943-4d3d-8c61-354d3dc9e900</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9f82b241-8090-41fe-bdd7-b19c099eb49e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5ffeefc5-6cee-41b1-b358-3140457e1181</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Yoda_Station/Keyclock/Post-condition</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
</TestSuiteEntity>
