<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Chevron_Tools</name>
   <tag></tag>
   <elementGuidId>dcf53f9c-c7c3-4090-b0da-c49933f7b388</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;app&quot;]/div/div[2]/nav/div[1]/div/div[2]/div[5]/div/div[1]/div[3]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>f4b71c74-fd9d-41c7-805d-9f2e7d883917</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1665651202598</value>
      <webElementGuid>de5553a4-9355-42d0-905b-0a54e08d86d6</webElementGuid>
   </webElementProperties>
</WebElementEntity>
