<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Chevron_Temp</name>
   <tag></tag>
   <elementGuidId>9dd90db4-1cfa-4bee-88a7-42370e1202a2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;app&quot;]/div/div[2]/nav/div[1]/div/div[2]/div[3]/div/div[1]/div[3]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>d473daf6-8f02-4302-80ef-fdadd1cfdc56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1665651070127</value>
      <webElementGuid>898899a6-bb43-404d-bb69-d5f0ddc86ef1</webElementGuid>
   </webElementProperties>
</WebElementEntity>
