<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Chevron_Infra</name>
   <tag></tag>
   <elementGuidId>50d1942b-7558-45be-9801-9153b0bf3f19</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;app&quot;]/div/div[2]/nav/div[1]/div/div[2]/div[3]/div/div[1]/div[3]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>4ee886ba-f981-4a7e-8323-7ae05cabb1eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1665651107006</value>
      <webElementGuid>9b6db483-bb0c-4dba-aa45-9a57539e2675</webElementGuid>
   </webElementProperties>
</WebElementEntity>
