<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Chevron_left_Flw_Doc</name>
   <tag></tag>
   <elementGuidId>1e14919d-aeb5-484b-aff0-a5ef76cdbaba</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;app&quot;]/div/div[2]/nav/div[1]/div/div[2]/div[2]/div/div[1]/div[3]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>ddc92d99-a231-4e9d-9f27-59ea9d3aa231</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1665651019610</value>
      <webElementGuid>11ab66cd-7054-4bd4-890a-985e0874ae16</webElementGuid>
   </webElementProperties>
</WebElementEntity>
