<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Flow_documentation_icon</name>
   <tag></tag>
   <elementGuidId>7aa26079-8bb4-4b1f-997a-913e3f8785db</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.v-icon.notranslate.mdi.mdi-file-document.theme--dark</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/div[2]/nav/div/div/div[2]/div[2]/div/div/div/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>28008cdf-6a19-4599-af13-905834539995</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>1ef576f2-abde-4255-8eff-a91793cca4b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>v-icon notranslate mdi mdi-file-document theme--dark</value>
      <webElementGuid>e7b3ffdf-1482-48bb-9543-27c1e15d1eca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;v-application--wrap&quot;]/div[2]/nav[@class=&quot;v-navigation-drawer v-navigation-drawer--fixed v-navigation-drawer--open theme--dark&quot;]/div[@class=&quot;v-navigation-drawer__content&quot;]/div[@class=&quot;v-list py-0 v-sheet v-sheet--tile theme--dark v-list--dense v-list--nav&quot;]/div[@class=&quot;v-list v-sheet v-sheet--tile theme--dark&quot;]/div[2]/div[@class=&quot;v-list-group v-list-group--no-action&quot;]/div[@class=&quot;v-list-group__header v-list-item v-list-item--link theme--dark&quot;]/div[@class=&quot;v-list-item__icon v-list-group__header__prepend-icon&quot;]/i[@class=&quot;v-icon notranslate mdi mdi-file-document theme--dark&quot;]</value>
      <webElementGuid>d724c93f-cb4a-473f-81e3-b96633a2442f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div[2]/nav/div/div/div[2]/div[2]/div/div/div/i</value>
      <webElementGuid>0375f6e6-55fc-43b0-bb5a-8632588f9637</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/div/i</value>
      <webElementGuid>c706f618-6309-410b-9d86-d0aa21ebb48d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
