<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Home_icon</name>
   <tag></tag>
   <elementGuidId>f44e8c1b-5eef-41eb-a591-47d50cff3c54</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.v-icon.notranslate.mdi.mdi-home.theme--dark</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/div[2]/nav/div/div/div[2]/div/a/div/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>386e38cb-b2bb-48a7-8f8b-742ca4e95630</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>e639de4f-84ba-41cf-be66-b2fe1a6bcc88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>v-icon notranslate mdi mdi-home theme--dark</value>
      <webElementGuid>c779493f-65f0-4855-be7e-1105cb63a2f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;v-application--wrap&quot;]/div[2]/nav[@class=&quot;v-navigation-drawer v-navigation-drawer--fixed v-navigation-drawer--open theme--dark&quot;]/div[@class=&quot;v-navigation-drawer__content&quot;]/div[@class=&quot;v-list py-0 v-sheet v-sheet--tile theme--dark v-list--dense v-list--nav&quot;]/div[@class=&quot;v-list v-sheet v-sheet--tile theme--dark&quot;]/div[1]/a[@class=&quot;v-list-item v-list-item--link theme--dark&quot;]/div[@class=&quot;v-list-item__icon&quot;]/i[@class=&quot;v-icon notranslate mdi mdi-home theme--dark&quot;]</value>
      <webElementGuid>36310ada-f3ec-4c92-8969-112484f3674d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div[2]/nav/div/div/div[2]/div/a/div/i</value>
      <webElementGuid>1dc1a1fa-d581-4834-8720-a251b3b251be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/div/i</value>
      <webElementGuid>b347778f-acbc-485f-adf9-1464339de5b0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
