<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>icon_logout</name>
   <tag></tag>
   <elementGuidId>afa4179f-ef19-42e7-bcb8-68498bb81900</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.v-list-item__icon > i.v-icon.notranslate.material-icons.theme--dark</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/div[2]/nav/div[2]/div/div/div/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>e98ebc39-191c-48cf-b639-06e70ff649e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>fea9241d-fcb9-4f04-8e8f-f4b404c38096</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>v-icon notranslate material-icons theme--dark</value>
      <webElementGuid>b21ccacc-281f-40ad-8859-91a0ec88f63f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>logout</value>
      <webElementGuid>d189e99b-23f9-4135-a796-f5914e55a6de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;v-application--wrap&quot;]/div[2]/nav[@class=&quot;v-navigation-drawer v-navigation-drawer--fixed v-navigation-drawer--open theme--dark&quot;]/div[@class=&quot;v-navigation-drawer__append&quot;]/div[@class=&quot;v-list v-sheet v-sheet--tile theme--dark&quot;]/div[@class=&quot;v-list-item v-list-item--link theme--dark&quot;]/div[@class=&quot;v-list-item__icon&quot;]/i[@class=&quot;v-icon notranslate material-icons theme--dark&quot;]</value>
      <webElementGuid>04c2dda7-91a1-477e-9f73-768da3b3eed4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div[2]/nav/div[2]/div/div/div/i</value>
      <webElementGuid>2c68f192-978a-4993-9bbb-570eab4f8447</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='About'])[1]/following::i[1]</value>
      <webElementGuid>382853ca-a371-4c99-8620-28dc9e8119df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Profile'])[1]/following::i[2]</value>
      <webElementGuid>10e36476-883c-4349-a87f-8fd11a975726</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Logout'])[1]/preceding::i[1]</value>
      <webElementGuid>2f9d6972-bc17-4bac-b86e-7f391652919f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Readme'])[1]/preceding::i[1]</value>
      <webElementGuid>3fc154b6-f7e4-4f1b-b640-1ab4b8edffac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='logout']/parent::*</value>
      <webElementGuid>b706f6a3-081c-46d8-b955-b6f63dc693c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/i</value>
      <webElementGuid>f090b7e9-35f5-4898-b365-329080134914</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//i[(text() = 'logout' or . = 'logout')]</value>
      <webElementGuid>6dbbb09c-e1d8-4af9-bcc5-baa5a14de560</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
