<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Create</name>
   <tag></tag>
   <elementGuidId>948e53d0-2f34-4384-ac7c-cd546b6795da</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.v-btn.v-btn--contained.theme--light.v-size--default.secondary</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table/thead/tr/th[6]/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>72b49978-aa35-4d24-9949-8aafd03708f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>028a3c57-dfbe-4e5f-8f94-7a4708e4a9c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>v-btn v-btn--contained theme--light v-size--default secondary</value>
      <webElementGuid>2383cc78-8573-408d-9392-e1459ff4d8ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
      Create
    </value>
      <webElementGuid>754704d3-988a-40d8-833f-68bb6a2c247b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;v-application--wrap&quot;]/main[@class=&quot;v-content&quot;]/div[@class=&quot;v-content__wrap&quot;]/div[@class=&quot;container container--fluid&quot;]/div[@class=&quot;container container--fluid&quot;]/div[@class=&quot;container container--fluid&quot;]/div[@class=&quot;v-data-table elevation-1 v-data-table--dense theme--light&quot;]/header[@class=&quot;v-sheet v-sheet--tile theme--light v-toolbar v-toolbar--flat&quot;]/div[@class=&quot;v-toolbar__content&quot;]/button[@class=&quot;v-btn v-btn--contained theme--light v-size--default secondary&quot;]</value>
      <webElementGuid>7ea3f230-41ea-4bba-8ea0-1bb14c24c810</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[4]</value>
      <webElementGuid>8add9db8-31f8-484c-9a2c-181677c3ef85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div[2]/div[2]/div/header/div/button[2]</value>
      <webElementGuid>aca65834-433f-4d56-aa27-1a6b15616a19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Yoda Flow sheet list'])[1]/following::button[2]</value>
      <webElementGuid>4b295eac-0428-4365-ad65-66dd79b05a3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Logout'])[1]/following::button[3]</value>
      <webElementGuid>1ac1f039-f920-4a63-9f99-af60e29a95e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Flow name'])[1]/preceding::button[1]</value>
      <webElementGuid>b857c4a9-dc70-4313-992f-5003280ae0b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]</value>
      <webElementGuid>5412fb88-499f-405a-95ee-18d71132aa15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = '
      Create
    ' or . = '
      Create
    ')]</value>
      <webElementGuid>f488eb0f-7a51-427a-8237-0e768a0c3e9f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
