<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Test</name>
   <tag></tag>
   <elementGuidId>15734f3f-0495-4936-b16a-044468381d46</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table/tbody</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
