<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_www.google.com</name>
   <tag></tag>
   <elementGuidId>f0108221-6852-4612-a66c-f3294c9c0fba</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']//table/tbody/tr[10]/td[2]/div/div/div[2][contains(text(),'www.google.com')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.v-list-item.v-list-item--dense.v-list-item--link.theme--light > div.v-list-item__content > div.v-list-item__subtitle</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>6e67985c-7a5f-4b3e-9e84-2476db82ee87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>v-list-item__subtitle</value>
      <webElementGuid>4e6b3208-cd3f-4ad8-801e-6b0555c630d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>www.google.com</value>
      <webElementGuid>d27487f1-94d0-49fc-98ae-7c504f96e9d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;v-application--wrap&quot;]/main[@class=&quot;v-content&quot;]/div[@class=&quot;v-content__wrap&quot;]/div[@class=&quot;container container--fluid&quot;]/div[@class=&quot;container container--fluid&quot;]/div[@class=&quot;v-tabs theme--dark&quot;]/div[@class=&quot;v-window v-item-group theme--light v-tabs-items&quot;]/div[@class=&quot;v-window__container&quot;]/div[@class=&quot;v-window-item v-window-item--active&quot;]/div[@class=&quot;mx-auto v-card v-sheet theme--light&quot;]/div[@class=&quot;v-card__text&quot;]/div[@class=&quot;v-data-table v-data-table--dense theme--light&quot;]/div[@class=&quot;v-data-table__wrapper&quot;]/table[1]/tbody[1]/tr[10]/td[2]/div[@class=&quot;v-list-item v-list-item--dense v-list-item--link theme--light&quot;]/div[@class=&quot;v-list-item__content&quot;]/div[@class=&quot;v-list-item__subtitle&quot;]</value>
      <webElementGuid>0a2c23b9-614d-4be9-a00d-11da7de2da43</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div[2]/div[2]/div[2]/div/div/div[2]/div/div/div/table/tbody/tr[10]/td[2]/div/div/div[2]</value>
      <webElementGuid>974ee987-e6fd-4f84-97f5-ed88dd7a044f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Test_Auto_label_Mapping'])[1]/following::div[1]</value>
      <webElementGuid>ee639ea2-3491-42d6-9730-316ea83433e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mappings (click on label to open)'])[1]/following::div[4]</value>
      <webElementGuid>f5eabcba-66b6-419c-ba41-b7fa6bfa4ad7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No objective and flow context specified.'])[1]/preceding::div[1]</value>
      <webElementGuid>d82c1630-8abb-40ab-bace-f1213eefdd60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No description specified.'])[1]/preceding::div[4]</value>
      <webElementGuid>e6430f0c-2c97-4bef-b727-bf73f713bb56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='www.google.com']/parent::*</value>
      <webElementGuid>79bfd230-5ca7-471f-b3a8-13646a0c5077</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/div/div/div[2]</value>
      <webElementGuid>883de141-9355-4141-b247-5b7d28c35f26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'www.google.com' or . = 'www.google.com')]</value>
      <webElementGuid>0e9e8ca5-e7d9-43d3-a0a2-c6f7c3854109</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
