<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Flow name_input-346</name>
   <tag></tag>
   <elementGuidId>bd24e23b-5b17-4ee9-b876-50697b4d03d7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-346</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//label[contains(text(),'Flow name*')]//following-sibling::input[@type='text']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>18b1ed91-b929-4b66-8b09-2679958a9134</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>47afe8b6-4cda-4808-86ac-8952cf0e59d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-346</value>
      <webElementGuid>a1b0645e-19e9-4a1c-9704-0505d3695aa4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ee92e243-69b4-424e-923b-9f7bee373390</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-346&quot;)</value>
      <webElementGuid>71ff4845-f997-4ae2-af8f-088440ff14fb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-346']</value>
      <webElementGuid>cd199349-29ca-4951-ae1f-22096e920e92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div/div/div[3]/form/div/div/div/div/input</value>
      <webElementGuid>297785ae-ebde-4261-90ac-cf5079047ade</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>1a1ce15b-e65c-46bc-a7bc-699206ce933b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-346' and @type = 'text']</value>
      <webElementGuid>be9d480d-b315-4e5c-8f20-1d4dcb0da74b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
