<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Created_Name</name>
   <tag></tag>
   <elementGuidId>013d338e-1f78-4b3b-bc7f-6aa6e8744fb8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;app&quot;]//table/tbody/tr/td[2][contains(text(),'RETAILDIAM_ANE_COR_Test_AUTO_account2admin')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
