<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Technical</name>
   <tag></tag>
   <elementGuidId>19d7f236-88ab-4f8a-bf07-0584dcebfa7f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>BASIC</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//label[(text() = 'Technical' or . = 'Technical')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>e24d4f89-9f44-45f6-8527-a9a3a49fa8a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>input-527</value>
      <webElementGuid>5efa4dac-bec0-4efe-86dc-0a4c05e268cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>v-label theme--light</value>
      <webElementGuid>73780a15-5dee-412b-8b1d-09563339a9e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Technical</value>
      <webElementGuid>5d784fbe-b7fe-4cca-b30a-83632f15b660</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;v-dialog__content v-dialog__content--active&quot;]/div[@class=&quot;v-dialog v-dialog--active&quot;]/div[@class=&quot;v-card v-sheet theme--light&quot;]/div[@class=&quot;v-card__text&quot;]/form[@class=&quot;v-form&quot;]/div[@class=&quot;container container--fluid&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col col-6&quot;]/div[@class=&quot;v-input theme--light v-input--selection-controls v-input--switch&quot;]/div[@class=&quot;v-input__control&quot;]/div[@class=&quot;v-input__slot&quot;]/label[@class=&quot;v-label theme--light&quot;]</value>
      <webElementGuid>7ae69154-8345-4554-879f-24bd0885d76c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div/div/div[2]/form/div/div[11]/div[2]/div/div/div/label</value>
      <webElementGuid>d33f3a89-2a23-404e-8dd0-f2420cbb5c5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Deprecated'])[1]/following::label[1]</value>
      <webElementGuid>8a4b29c2-e1dd-41d9-a2be-f62cbd7823aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Logical Flow Ids'])[1]/following::label[2]</value>
      <webElementGuid>6812938e-acca-405b-8843-8e2c1c7142d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Overview (max 500 Ko)'])[1]/preceding::label[1]</value>
      <webElementGuid>2ab68f8a-1ec3-4f0d-855a-a04c6b58678d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='​'])[1]/preceding::label[2]</value>
      <webElementGuid>0891c0d2-9d27-4017-85f4-053dbf0a8cc1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Technical']/parent::*</value>
      <webElementGuid>252d7010-df71-418b-95d2-8b8a00762c35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/div[2]/div/div/div/label</value>
      <webElementGuid>64398bc6-517d-4bef-b145-053f3b08acab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Technical' or . = 'Technical')]</value>
      <webElementGuid>820d5e22-269e-4b47-84a6-1358c194f889</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
