<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Key-uid2</name>
   <tag></tag>
   <elementGuidId>a0509f13-d3ac-4b44-9b36-09d920c838d2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>//*[@id=&quot;view&quot;]/div[1]/form/table/tbody/tr[14]/td[1][contains(text(),'uid')]</value>
      </entry>
      <entry>
         <key>BASIC</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;attribute-uid&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
