<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Key-orga-project</name>
   <tag></tag>
   <elementGuidId>377ce13b-6e9e-4da8-a315-78f472b438f3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;view&quot;]/div[1]/form/table/tbody/tr[9]/td[1][contains(text(),'orga-project')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
