<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Value-Country</name>
   <tag></tag>
   <elementGuidId>bb242967-1361-4e07-9c30-0c4d79bacc90</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#attribute-country</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
