<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Value-is-corporate2</name>
   <tag></tag>
   <elementGuidId>9b59fc58-b99f-44c9-b790-781490028883</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#attribute-is-corporate</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
