<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Logo_Yoda</name>
   <tag></tag>
   <elementGuidId>e0622217-fa4c-4ba5-9baa-44ffd6bd7792</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.v-responsive__content</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='bookmark']/header/div/div/div[@class='v-responsive__content']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>297b4aeb-0648-4c19-bc1a-6e016edb016f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>v-responsive__content</value>
      <webElementGuid>81433e53-f9b5-49e1-b2ee-7b98e7da084c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bookmark&quot;)/header[@class=&quot;v-sheet v-sheet--tile theme--dark v-toolbar v-toolbar--extended v-toolbar--flat&quot;]/div[@class=&quot;v-toolbar__content&quot;]/div[@class=&quot;v-responsive v-image&quot;]/div[@class=&quot;v-responsive__content&quot;]</value>
      <webElementGuid>3b472e09-14df-49f0-99d6-d87177125d64</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='bookmark']/header/div/div/div[3]</value>
      <webElementGuid>14efe86d-667a-4f20-ba0d-c53658b32951</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]</value>
      <webElementGuid>cbd52595-8973-4482-b62e-0c91d1eab246</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
