<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Menu_PROD</name>
   <tag></tag>
   <elementGuidId>233922fc-e746-4bb5-b229-7a9fdef7a1a3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='bookmark']/header/div[2]/div/div/div[2]/div/div[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>c474de49-9781-414a-98b6-5936b92bc174</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>eb1a9534-3d33-4e38-8647-f7fe72e65690</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>8f6a78b3-cb61-40a3-b638-36f82457ab50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>4730bcb1-2ce2-45a3-94b3-f8199f379398</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>v-tab</value>
      <webElementGuid>c7a2ab55-7f8b-4266-abfb-ecb193d1c63a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
          PROD
        </value>
      <webElementGuid>45159806-79c3-46e8-9dbf-13669ab875e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bookmark&quot;)/header[@class=&quot;v-sheet v-sheet--tile theme--dark v-toolbar v-toolbar--extended v-toolbar--flat&quot;]/div[@class=&quot;v-toolbar__extension&quot;]/div[@class=&quot;v-tabs v-tabs--centered theme--dark&quot;]/div[@class=&quot;v-item-group theme--dark v-slide-group v-tabs-bar v-tabs-bar--is-mobile white--text green darken-3&quot;]/div[@class=&quot;v-slide-group__wrapper&quot;]/div[@class=&quot;v-slide-group__content v-tabs-bar__content&quot;]/div[@class=&quot;v-tab&quot;]</value>
      <webElementGuid>c556d5e6-0e90-4495-a097-2e4ff5d81b9b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='bookmark']/header/div[2]/div/div/div[2]/div/div[3]</value>
      <webElementGuid>5ed79161-b395-4fd8-bb2a-2ff8b7eb0dab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='COMMON'])[1]/following::div[1]</value>
      <webElementGuid>b0919519-61f4-4428-a01f-995163be76e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='The only one portal to access to all your Yoda services!'])[1]/following::div[10]</value>
      <webElementGuid>36af63ac-296d-40ce-b160-477c52eff295</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='UAT'])[1]/preceding::div[1]</value>
      <webElementGuid>22c508ec-8bda-4811-ae8f-c7c06e67d3b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Capture object:'])[1]/preceding::div[13]</value>
      <webElementGuid>14b8476a-046a-44cd-bff7-7e445a45dcbb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='PROD']/parent::*</value>
      <webElementGuid>738eaabd-abeb-4a51-9d6b-e58cd725feff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[3]</value>
      <webElementGuid>bebc8acf-6f43-4fc6-9460-1a148f084c0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '
          PROD
        ' or . = '
          PROD
        ')]</value>
      <webElementGuid>67b64e43-97c7-47a2-a6d2-936740802df1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
