<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Titre2_Portal_Yoda</name>
   <tag></tag>
   <elementGuidId>3b2aceff-99ea-46b9-8df9-a851717a2690</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.subtitle-2.font-italic</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>.//span[text()='The only one portal to access to all your Yoda services!']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>0932a208-4e52-44a5-b692-e88a07370f55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>subtitle-2 font-italic</value>
      <webElementGuid>e102b437-cf4f-4685-be16-9acec979e595</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>The only one portal to access to all your Yoda services!</value>
      <webElementGuid>800cc1b8-fd7f-489f-b79a-105c965a8cd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bookmark&quot;)/header[@class=&quot;v-sheet v-sheet--tile theme--dark v-toolbar v-toolbar--extended v-toolbar--flat&quot;]/div[@class=&quot;v-toolbar__content&quot;]/div[@class=&quot;v-toolbar__title&quot;]/span[@class=&quot;subtitle-2 font-italic&quot;]</value>
      <webElementGuid>a05febe4-4200-405b-beee-889c3fb9b019</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='bookmark']/header/div/div[2]/span</value>
      <webElementGuid>7ec8fe08-7980-454f-b687-5b04b92e82b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='COMMON'])[1]/preceding::span[1]</value>
      <webElementGuid>c98ac528-7236-4a6d-ba56-5040888cb5f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PROD'])[1]/preceding::span[1]</value>
      <webElementGuid>7a9c09e2-389a-4442-bd4b-5adae9fe7b27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='The only one portal to access to all your Yoda services!']/parent::*</value>
      <webElementGuid>4b333957-5f1f-4817-8564-ac0b874da905</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span</value>
      <webElementGuid>8b9856f2-35e1-4a05-b730-0a69954e8c00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'The only one portal to access to all your Yoda services!' or . = 'The only one portal to access to all your Yoda services!')]</value>
      <webElementGuid>e8bb0381-2197-4e0f-9dea-01770dd27b15</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
