<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Yoda_Wiki_Link</name>
   <tag></tag>
   <elementGuidId>82ef2e99-61ab-4a91-bc5b-91e2c222d391</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@href = 'https://sites.google.com/auchan.com/yoda-wiki-2/home' and @title = 'Yoda Wiki']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='bookmark']/div/div/div/div/div/div[2]/div/a</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>8dd4f850-4737-48f7-ad57-50f7e152323c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://sites.google.com/auchan.com/yoda-wiki-2/home</value>
      <webElementGuid>7a2a3781-822c-4133-8de8-600295254a5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>6868ed54-815b-4246-bff8-87138e83d5ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Yoda Wiki</value>
      <webElementGuid>d283abcb-6032-4692-b581-aa2cf36e5455</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hexagon__link</value>
      <webElementGuid>14dd3771-6a00-4c25-91be-81d9bfc4b9d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bookmark&quot;)/div[@class=&quot;v-window v-item-group theme--dark v-tabs-items&quot;]/div[@class=&quot;v-window__container&quot;]/div[@class=&quot;v-window-item v-window-item--active&quot;]/div[@class=&quot;hexagon-background&quot;]/div[@class=&quot;hexagon-container&quot;]/div[@class=&quot;hexagon&quot;]/div[@class=&quot;hexagon__inner hexagon-COMMON&quot;]/a[@class=&quot;hexagon__link&quot;]</value>
      <webElementGuid>8345a2f4-2559-4a8d-b309-54046eccbf8b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='bookmark']/div/div/div/div/div/div[2]/div/a</value>
      <webElementGuid>51c4deba-eeff-42b1-a5a4-dc0e7b279b26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://sites.google.com/auchan.com/yoda-wiki-2/home')]</value>
      <webElementGuid>fbddd9ff-8727-4bde-8e34-75fcc3225b07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/a</value>
      <webElementGuid>3cf9703a-aba2-4fe7-a224-ef68e423f69c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://sites.google.com/auchan.com/yoda-wiki-2/home' and @title = 'Yoda Wiki']</value>
      <webElementGuid>4f368f8a-8f95-4cc2-bdf2-595ee16bff18</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
