<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Yoda_Station_Link</name>
   <tag></tag>
   <elementGuidId>85c59c24-27d1-46e7-919d-ab94d28fa0da</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.hexagon__link</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='bookmark']/div/div/div/div/div/div/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>3ecbd3db-9106-45d4-a739-bce4630afdaa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://station.yep-sandbox.np.internal.auchan.com/</value>
      <webElementGuid>26c1e2e5-1d58-4698-bbe4-8e97fe22571d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>2ea046e2-5ece-45f0-8d37-8da47184b004</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Yoda Station</value>
      <webElementGuid>a90322e0-13ad-4f9c-9cef-ae10281466e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hexagon__link</value>
      <webElementGuid>23828485-a5b8-49b9-b988-13c231ee2337</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bookmark&quot;)/div[@class=&quot;v-window v-item-group theme--dark v-tabs-items&quot;]/div[@class=&quot;v-window__container&quot;]/div[@class=&quot;v-window-item v-window-item--active&quot;]/div[@class=&quot;hexagon-background&quot;]/div[@class=&quot;hexagon-container&quot;]/div[@class=&quot;hexagon&quot;]/div[@class=&quot;hexagon__inner hexagon-COMMON&quot;]/a[@class=&quot;hexagon__link&quot;]</value>
      <webElementGuid>0feb05e3-1900-4649-9b9d-0be6200f683c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='bookmark']/div/div/div/div/div/div/div/a</value>
      <webElementGuid>67d5c989-3a4e-463f-a310-dc8f1569bffe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://station.yep-sandbox.np.internal.auchan.com/')]</value>
      <webElementGuid>b48419d8-1ba5-43b0-9e8f-4105218cd670</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a</value>
      <webElementGuid>b45c81c2-40ce-4bf6-bbe9-0e3ae1e89f04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://station.yep-sandbox.np.internal.auchan.com/' and @title = 'Yoda Station']</value>
      <webElementGuid>40ad0b16-ba85-4e8a-af90-88e874e246a9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
