<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Next</name>
   <tag></tag>
   <elementGuidId>bd926584-c602-4fa2-a517-591e9b571bda</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.ping-button.normal.allow</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@onclick='postOk();']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>49de07ed-be06-41e8-971a-c6b544653729</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>postOk();</value>
      <webElementGuid>9921aaec-5bce-47c5-bc6e-e3adba947ba8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ping-button normal allow</value>
      <webElementGuid>70ac7169-a7eb-4601-be5b-e00e1ab084ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>authentication.identifier.template. signInButtonTitle</value>
      <webElementGuid>eee2ee00-b0ff-4456-af20-3353d23cc331</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                Next
                </value>
      <webElementGuid>c450be90-40e1-4353-a944-bb6d7fae3715</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;postButton&quot;)/a[@class=&quot;ping-button normal allow&quot;]</value>
      <webElementGuid>f3a8276f-934e-4a6d-8a8f-323424832356</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@onclick='postOk();']</value>
      <webElementGuid>71d4878a-3be6-4ff5-8909-9b0a0eac37f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='postButton']/a</value>
      <webElementGuid>91468cc1-677a-461a-92c4-8f61294e9f07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Next')]</value>
      <webElementGuid>805260e2-8b45-4bc1-bddf-cc120fd4ae35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='!'])[1]/following::a[1]</value>
      <webElementGuid>924f3ae2-2cab-4b2a-8217-5c81274c9195</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='click here.'])[1]/preceding::a[1]</value>
      <webElementGuid>7717cbed-0e7f-4f0f-9c0f-4342a022a6d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Capture object:'])[1]/preceding::a[2]</value>
      <webElementGuid>fc583d74-95cf-44d2-9932-a7f0e91ea045</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Next']/parent::*</value>
      <webElementGuid>8c3dcc22-10c8-4ac6-993e-00b18ef01d0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a</value>
      <webElementGuid>7144c5e4-8163-4afb-b350-9c589b88f767</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@title = 'authentication.identifier.template. signInButtonTitle' and (text() = '
                Next
                ' or . = '
                Next
                ')]</value>
      <webElementGuid>64601cbd-970c-417e-9eb5-42d70e947ecd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
